name: Refactor
description: コードの整理や改善を提案する
title: "[Refactor] "
labels: ["refactor"]

body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: どの部分をリファクタリングするか簡単に説明してください

  - type: textarea
    id: details
    attributes:
      label: 詳細
      description: 具体的にどう改善する予定かを書いてください

  - type: checkboxes
    id: parent-issue
    attributes:
      label: 親Issueとして扱う
      options:
        - label: このIssueは親（Epic）です

  - type: textarea
    id: children
    attributes:
      label: 子Issueのリンク
      description: 関連する子Issueがあれば `#番号` でリンクを追加してください

  - type: input
    id: branch
    attributes:
      label: ブランチ名（コピー用）
      description: `git checkout -b` の後に貼り付けてください
      value: refactor/issue-<番号>-短い説明